# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""
Lockfile generation for reproducible benchmark runs.

The lockfile is the original recipe YAML with a `lock:` section appended.
It captures everything needed to understand and reproduce a run:

- The recipe (unchanged, with aliases and identity block)
- lock.slurm: where and how the job ran (job ID, cluster, nodes)
- lock.resolved: what aliases mapped to (local paths)
- lock.verification: identity checks (did runtime match declarations?)
- lock.fingerprints: per-worker runtime environment (GPU, frameworks, packages)
- lock.results: benchmark metrics (throughput, latency)

The lockfile IS a valid recipe — `srtctl apply recipe.lock.yaml` works.
When applying a lockfile, srtctl compares the new run against lock.fingerprints.

All operations are fault-tolerant — lockfile writing never blocks or fails a job.
"""

from __future__ import annotations

import contextlib
import getpass
import hashlib
import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any

import yaml

from srtctl.core.fingerprint import load_fingerprint
from srtctl.core.resource_snapshot import load_resource_snapshot

if TYPE_CHECKING:
    from srtctl.core.schema import SrtConfig

logger = logging.getLogger(__name__)

# Lockfile format version — bump when the structure changes
_LOCKFILE_VERSION = 2

# Comment inserted above the lock section
_LOCK_COMMENT = """\

# ============================================================================
# Lock section — generated by srtctl after a run. DO NOT edit manually.
#
# This records exactly what happened when this recipe was executed.
# To reproduce on another cluster:
#   1. Ensure your srtslurm.yaml has the same model/container aliases
#   2. Run: srtctl apply -f this-file.lock.yaml
#   3. srtctl will compare your runtime against the original fingerprints
#
# The recipe above is unchanged from what the author wrote.
# ============================================================================
"""

# SLURM environment variables to capture.
_SLURM_ENV_KEYS = [
    ("job_id", "SLURM_JOB_ID"),
    ("job_name", "SLURM_JOB_NAME"),
    ("cluster", "SLURM_CLUSTER_NAME"),
    ("account", "SLURM_JOB_ACCOUNT"),
    ("partition", "SLURM_JOB_PARTITION"),
    ("nodelist", "SLURM_JOB_NODELIST"),
    ("num_nodes", "SLURM_JOB_NUM_NODES"),
    ("gpus_per_node", "SLURM_GPUS_PER_NODE"),
    ("cpus_per_node", "SLURM_JOB_CPUS_PER_NODE"),
    ("cpus_on_node", "SLURM_CPUS_ON_NODE"),
    ("cpus_per_task", "SLURM_CPUS_PER_TASK"),
    ("cpus_per_gpu", "SLURM_CPUS_PER_GPU"),
    ("num_tasks", "SLURM_NTASKS"),
    ("time_limit", "SLURM_TIMELIMIT"),
]


def collect_slurm_context() -> dict[str, Any]:
    """Collect SLURM job context from environment variables."""
    ctx: dict[str, Any] = {}

    for key, env_var in _SLURM_ENV_KEYS:
        val = os.environ.get(env_var)
        if val is not None:
            ctx[key] = val

    with contextlib.suppress(Exception):
        ctx["user"] = getpass.getuser()

    ctx["cwd"] = str(Path.cwd())

    srtctl_root = os.environ.get("SRTCTL_ROOT")
    if srtctl_root:
        ctx["srtctl_root"] = srtctl_root

    with contextlib.suppress(Exception):
        import subprocess

        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            timeout=2,
            cwd=srtctl_root or None,
            check=False,
        )
        if result.returncode == 0:
            ctx["srtctl_commit"] = result.stdout.strip()

    return ctx


def collect_worker_fingerprints(log_dir: Path) -> dict[str, Any] | None:
    """Load per-worker fingerprint files into a dict keyed by worker name."""
    try:
        fp_files = sorted(log_dir.glob("fingerprint_*.json"))
    except Exception as e:  # noqa: BLE001
        logger.debug("Failed to glob fingerprint files in %s: %s", log_dir, e)
        return None

    if not fp_files:
        return None

    result: dict[str, Any] = {}
    for fp_file in fp_files:
        fp = load_fingerprint(fp_file)
        if fp is not None:
            worker_key = fp_file.stem.removeprefix("fingerprint_")
            result[worker_key] = fp

    return result if result else None


def build_lock_section(
    config: SrtConfig,
    worker_fingerprints: dict[str, Any] | None = None,
    resolved_log_dir: Path | None = None,
    verification: list[Any] | None = None,
    results: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Build the lock: section dict.

    Args:
        config: The resolved SrtConfig.
        worker_fingerprints: Per-worker fingerprints keyed by worker name.
        resolved_log_dir: Actual log directory path (resolved from template).
        verification: List of IdentityCheckResult from verify_identity().
        results: Benchmark results from rollup (if available).
    """
    # Build verification summary
    verification_dict = None
    if verification:
        verified = [r for r in verification if r.passed and "not verifiable" not in r.message]
        declared = [r for r in verification if r.passed and "not verifiable" in r.message]
        fails = [r for r in verification if not r.passed]

        def _status(r: Any) -> str:
            if not r.passed:
                return "FAIL"
            return "DECLARED" if "not verifiable" in r.message else "OK"

        parts = []
        if verified:
            parts.append(f"{len(verified)} verified")
        if declared:
            parts.append(f"{len(declared)} declared")
        if fails:
            parts.append(f"{len(fails)} FAILED")

        verification_dict = {
            "result": ", ".join(parts),
            "verified": len(verified),
            "declared": len(declared),
            "failed": len(fails),
            "checks": [{"field": r.field, "status": _status(r), "message": r.message} for r in verification],
        }

    # Record what aliases resolved to
    resolved = {
        "model_path": config.model.path,
        "container_path": config.model.container,
    }
    if resolved_log_dir:
        resolved["log_dir"] = str(resolved_log_dir)

    lock: dict[str, Any] = {
        "version": _LOCKFILE_VERSION,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "slurm": collect_slurm_context(),
        "resolved": resolved,
    }

    if verification_dict:
        lock["verification"] = verification_dict
    if worker_fingerprints:
        lock["fingerprints"] = worker_fingerprints
    if resolved_log_dir and (resource_snapshot := load_resource_snapshot(resolved_log_dir)):
        lock["resource_snapshot"] = resource_snapshot
    if results:
        lock["results"] = results

    return lock


def write_lockfile(
    output_dir: Path,
    config: SrtConfig,
    log_dir: Path | None = None,
    verification: list[Any] | None = None,
    results: dict[str, Any] | None = None,
) -> bool:
    """Write recipe.lock.yaml — the original recipe with a lock: section appended.

    Called twice per job:
    1. At job start (log_dir=None) — writes recipe + lock with SLURM context
    2. At job end (log_dir set) — rewrites with fingerprints + verification + results

    Returns True on success, False on any failure. Never raises.
    """
    try:
        # Read the original recipe from the output directory
        recipe_path = output_dir / "config.yaml"
        if recipe_path.exists():
            recipe_text = recipe_path.read_text()
            # Strip any existing lock: section (from re-runs of lockfiles)
            recipe_text = _strip_lock_section(recipe_text)
        else:
            # Fallback: serialize the config (loses comments/formatting)
            from srtctl.core.schema import SrtConfig

            config_dict = SrtConfig.Schema().dump(config)
            config_dict.pop("lock", None)
            recipe_text = yaml.dump(config_dict, default_flow_style=False, sort_keys=False)

        # Build the lock section
        fingerprints = collect_worker_fingerprints(log_dir) if log_dir else None
        lock_data = build_lock_section(
            config,
            fingerprints,
            resolved_log_dir=log_dir,
            verification=verification,
            results=results,
        )

        # Compute integrity hash over the lock content (before adding the hash itself)
        lock_content_yaml = yaml.dump(lock_data, default_flow_style=False, sort_keys=True)
        lock_data["integrity"] = hashlib.sha256(lock_content_yaml.encode()).hexdigest()

        # Append lock section to recipe
        lock_yaml = yaml.dump({"lock": lock_data}, default_flow_style=False, sort_keys=False)
        lockfile_text = recipe_text.rstrip() + "\n" + _LOCK_COMMENT + lock_yaml

        lockfile_path = output_dir / "recipe.lock.yaml"
        lockfile_path.write_text(lockfile_text)
        logger.info("Wrote lockfile: %s", lockfile_path)
        return True
    except Exception as e:  # noqa: BLE001
        logger.warning("Failed to write lockfile: %s", e)
        return False


def generate_reproduction_report(
    prev_lock: dict[str, Any],
    new_fingerprints: dict[str, Any],
    new_results: dict[str, Any] | None = None,
) -> tuple[list[str], list[str], list[str]]:
    """Compare a new run's fingerprints against a previous lockfile's data.

    Compares per-worker: each worker in the previous run is matched against
    the same worker key in the new run. Detects added/removed workers and
    per-worker environment differences.

    Args:
        prev_lock: The lock: section from the previous lockfile.
        new_fingerprints: Per-worker fingerprints from the new run.
        new_results: Benchmark rollup from the new run (optional).

    Returns:
        Tuple of (summary_lines, report_lines, issues).
        - summary_lines: short output for sweep log
        - report_lines: full report for reproduction-report.txt
        - issues: list of problems found
    """
    import re

    from srtctl.core.fingerprint import _parse_pip_packages

    prev_fps = prev_lock.get("fingerprints", {})
    # TODO: prev_results = prev_lock.get("results") — once rollup format is standardized
    if not prev_fps or not new_fingerprints:
        return [], ["No fingerprints available for comparison."], []

    report_lines: list[str] = []
    summary_lines: list[str] = []
    issues: list[str] = []

    def _short(key: str, val: Any) -> str:
        if key == "cuda_version" and isinstance(val, str) and "release" in val:
            m = re.search(r"release ([\d.]+)", val)
            return m.group(1) if m else str(val)
        if key == "nccl_version" and isinstance(val, str) and val.startswith("("):
            return val.strip("()").replace(", ", ".")
        return str(val)

    def _compare(key: str, prev_val: Any, new_val: Any, prefix: str = "") -> str:
        prev_s = _short(key, prev_val) if prev_val else "?"
        new_s = _short(key, new_val) if new_val else "?"
        match = prev_s == new_s
        icon = "OK" if match else "!!"
        label = f"{prefix}{key}" if prefix else key
        line = f"  {icon}  {label}: {prev_s} == {new_s}" if match else f"  {icon}  {label}: {prev_s} != {new_s}"
        if not match:
            issues.append(f"{label}: {prev_s} -> {new_s}")
        return line

    def _compare_worker(
        worker: str,
        prev_fp: dict[str, Any],
        new_fp: dict[str, Any],
        to_summary: bool = True,
    ) -> None:
        """Compare a single worker pair — appends to report_lines and optionally summary_lines."""
        # Hardware
        prev_gpus = prev_fp.get("gpu", {})
        new_gpus = new_fp.get("gpu", {})
        prev_gpu_name = prev_gpus.get("gpus", [{}])[0].get("name", "?") if prev_gpus.get("gpus") else "?"
        new_gpu_name = new_gpus.get("gpus", [{}])[0].get("name", "?") if new_gpus.get("gpus") else "?"
        prev_gpu_count = len(prev_gpus.get("gpus", []))
        new_gpu_count = len(new_gpus.get("gpus", []))

        report_lines.append("  Hardware:")
        line = _compare("gpu", f"{prev_gpu_count}x {prev_gpu_name}", f"{new_gpu_count}x {new_gpu_name}")
        report_lines.append(f"  {line}")
        if to_summary:
            summary_lines.append(line)
        line = _compare("driver", prev_gpus.get("driver"), new_gpus.get("driver"))
        report_lines.append(f"  {line}")
        if to_summary:
            summary_lines.append(line)

        # Environment
        report_lines.append("  Environment:")
        for key in ["arch", "python_version", "cuda_version", "nccl_version", "os"]:
            line = _compare(key, prev_fp.get(key), new_fp.get(key))
            report_lines.append(f"  {line}")
            if to_summary:
                summary_lines.append(line)

        # Frameworks
        prev_fw = prev_fp.get("frameworks", {})
        new_fw = new_fp.get("frameworks", {})
        if prev_fw or new_fw:
            report_lines.append("  Frameworks:")
            for name in sorted(set(prev_fw) | set(new_fw)):
                line = _compare(name, prev_fw.get(name), new_fw.get(name))
                report_lines.append(f"  {line}")
                if to_summary:
                    summary_lines.append(line)

        # Env vars (report only)
        prev_env = prev_fp.get("env", {})
        new_env = new_fp.get("env", {})
        all_env_keys = sorted(set(prev_env) | set(new_env))
        env_diffs = [
            f"    !!  {k}: {prev_env.get(k)} -> {new_env.get(k)}"
            for k in all_env_keys
            if prev_env.get(k) != new_env.get(k)
        ]
        report_lines.append(f"  Env Vars: {len(all_env_keys)} compared, {len(env_diffs)} differ")
        if env_diffs:
            report_lines.extend(env_diffs)
            issues.append(f"{worker}: env vars differ ({len(env_diffs)})")

        # Pip packages (report only)
        prev_pkgs = _parse_pip_packages(prev_fp.get("pip_packages", {}))
        new_pkgs = _parse_pip_packages(new_fp.get("pip_packages", {}))
        all_pkg_names = sorted(set(prev_pkgs) | set(new_pkgs))
        pkg_changed, pkg_added, pkg_removed, pkg_matched = [], [], [], 0
        for name in all_pkg_names:
            pv, nv = prev_pkgs.get(name), new_pkgs.get(name)
            if pv and nv and pv == nv:
                pkg_matched += 1
            elif pv and nv:
                pkg_changed.append(f"    !!  {name}: {pv} -> {nv}")
            elif pv:
                pkg_removed.append(f"    --  {name}: {pv} (removed)")
            else:
                pkg_added.append(f"    ++  {name}: {nv} (added)")
        report_lines.append(
            f"  Pip: {pkg_matched} match, {len(pkg_changed)} changed, "
            f"{len(pkg_added)} added, {len(pkg_removed)} removed"
        )
        report_lines.extend(pkg_changed)
        report_lines.extend(pkg_added)
        report_lines.extend(pkg_removed)
        if pkg_changed or pkg_added or pkg_removed:
            issues.append(
                f"{worker}: pip packages differ "
                f"({len(pkg_changed)} changed, {len(pkg_added)} added, {len(pkg_removed)} removed)"
            )

    # --- Header ---
    prev_job = prev_lock.get("slurm", {}).get("job_id", "?")
    report_lines.append("=" * 70)
    report_lines.append("Reproduction Report")
    report_lines.append(f"Comparing against lockfile from job {prev_job}")
    report_lines.append("=" * 70)

    # --- Worker topology ---
    prev_workers = sorted(prev_fps.keys())
    new_workers = sorted(new_fingerprints.keys())
    report_lines.append("")
    report_lines.append(f"Workers: previous={prev_workers}, current={new_workers}")
    if prev_workers != new_workers:
        issues.append(f"Worker topology changed: {prev_workers} -> {new_workers}")
        summary_lines.append(f"  !!  workers: {prev_workers} != {new_workers}")

    # --- Per-worker comparison ---
    matched_workers = sorted(set(prev_workers) & set(new_workers))
    only_prev = sorted(set(prev_workers) - set(new_workers))
    only_new = sorted(set(new_workers) - set(prev_workers))

    for worker in matched_workers:
        report_lines.append("")
        report_lines.append(f"[{worker}]")
        # Only add to summary for the first worker (avoid noise for identical workers)
        _compare_worker(worker, prev_fps[worker], new_fingerprints[worker], to_summary=(worker == matched_workers[0]))

    for worker in only_prev:
        report_lines.append("")
        report_lines.append(f"[{worker}] REMOVED (was in previous run)")
        issues.append(f"Worker {worker} removed")

    for worker in only_new:
        report_lines.append("")
        report_lines.append(f"[{worker}] ADDED (not in previous run)")
        issues.append(f"Worker {worker} added")

    # --- Results ---
    # TODO: compare benchmark results once rollup format is standardized.

    # --- Summary ---
    report_lines.append("")
    report_lines.append("=" * 70)
    if issues:
        report_lines.append(f"ISSUES FOUND: {len(issues)}")
        for issue in issues:
            report_lines.append(f"  - {issue}")
    else:
        report_lines.append("No issues found. Environment is equivalent to the original run.")
    report_lines.append("=" * 70)

    return summary_lines, report_lines, issues


def _strip_lock_section(yaml_text: str) -> str:
    """Remove the top-level lock: section from YAML text.

    Only matches 'lock:' at column 0 (top-level key) to avoid stripping
    nested fields like 'model: {lock: value}'. Also strips the preceding
    comment banner.
    """
    lines = yaml_text.splitlines(keepends=True)
    result = []
    in_lock = False
    for line in lines:
        # Only match lock: at the START of a line (top-level YAML key)
        if not in_lock and (line.startswith("lock:") or "Lock section — generated by srtctl" in line):
            in_lock = True
            # Strip preceding blank lines and comment banner
            while result and (result[-1].strip() == "" or result[-1].strip().startswith("# ===")):
                result.pop()
            continue
        if in_lock:
            continue
        result.append(line)
    return "".join(result)


def verify_lock_integrity(lock_data: dict[str, Any]) -> bool:
    """Verify that a lock section hasn't been tampered with.

    Recomputes the SHA256 hash over the lock content (excluding the integrity
    field itself) and compares against the stored hash.

    Returns True if the hash matches, False if tampered or no hash present.
    """
    stored_hash = lock_data.get("integrity")
    if not stored_hash:
        return False

    # Recompute hash without the integrity field
    check_data = {k: v for k, v in lock_data.items() if k != "integrity"}
    content_yaml = yaml.dump(check_data, default_flow_style=False, sort_keys=True)
    computed_hash = hashlib.sha256(content_yaml.encode()).hexdigest()

    return computed_hash == stored_hash


def load_lockfile_fingerprints(path: Path) -> dict[str, Any] | None:
    """Load per-worker fingerprints from a lockfile, output directory, or raw JSON."""
    try:
        if path.is_dir():
            lockfile = path / "recipe.lock.yaml"
            if lockfile.exists():
                return _load_fingerprints_from_lockfile(lockfile)
            logs_dir = path / "logs"
            if logs_dir.is_dir():
                return collect_worker_fingerprints(logs_dir)
            return collect_worker_fingerprints(path)

        if path.suffix in (".yaml", ".yml"):
            return _load_fingerprints_from_lockfile(path)

        if path.suffix == ".json":
            fp = load_fingerprint(path)
            if fp is not None:
                worker_key = path.stem.removeprefix("fingerprint_") or "worker"
                return {worker_key: fp}
            return None

        return None
    except Exception as e:  # noqa: BLE001
        logger.debug("Failed to load fingerprints from %s: %s", path, e)
        return None


def _load_fingerprints_from_lockfile(path: Path) -> dict[str, Any] | None:
    """Extract per-worker fingerprints from a lockfile YAML."""
    try:
        data = yaml.safe_load(path.read_text())
        if not isinstance(data, dict):
            return None
        # New format: lock.fingerprints
        lock = data.get("lock")
        if isinstance(lock, dict):
            fps = lock.get("fingerprints")
            if isinstance(fps, dict):
                return fps
        # Legacy format: top-level fingerprints
        fps = data.get("fingerprints")
        if isinstance(fps, dict):
            return fps
        fp = data.get("fingerprint")
        if isinstance(fp, dict):
            return {"worker": fp}
        return None
    except Exception as e:  # noqa: BLE001
        logger.debug("Failed to parse lockfile %s: %s", path, e)
        return None
